apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: custom-fast-api
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/gcr-tut/custom-fastapi/custom-fastapi:latest
          env:
          ports:
            - containerPort: 4000